var Extasy = {
    game: Game,
    loopManager:LoopManager,
    assetManager: AssetManager,
    entityManager: EntityManager,
    stateManager: StateManager,
    cameraManager: CameraManager,
    inputManager: InputManager,
    renderManager: RenderManager,
    physicsManager: PhysicsManager,
    timeManager: TimeManager,
    mathManager: MathManager,
    entity: Entity,
    state: State,
    camera: Camera,
    spriteSheet: SpriteSheet,
    sprite: Sprite,
    rectangle: Rectangle,
    text: Text,
    circle: Circle,
    polygon: Polygon,
    regularPolygon: RegularPolygon,
    tileSprite: TileSprite,
    timer: Timer
};