var Extasy = {
    game: Game,
    loopManager:LoopManager,
    assetManager: AssetManager,
    entityManager: EntityManager,
    stateManager: StateManager,
    cameraManager: CameraManager,
    renderManager: RenderManager,
    physicsManager: PhysicsManager,
    timeManager: TimeManager,
    entity: Entity,
    state: State,
    inputManager: InputManager,
    spriteSheet: SpriteSheet,
    sprite: Sprite,
    rectangle: Rectangle,
    circle: Circle,
    polygon: Polygon,
    tileSprite: TileSprite,
    timer: Timer,
    controller: Controller
};